import { twMerge } from 'tailwind-merge';
import '../styles/globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import { Providers } from '@/components/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body
        className={twMerge(
          inter.className,
          'bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 min-h-screen flex flex-col text-sm'
        )}
      >
        <Toaster
          toastOptions={{ className: 'dark:bg-gray-700 dark:text-gray-100' }}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
